[package]
name = "jiraify"
version = "0.1.0"
authors = ["Stephen Kong <stephen.kong@fariaedu.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "2.33.0"
structopt = "0.3.5"